pipeline {
    agent any
    environment {
        PATH = "/usr/share/maven:$PATH"
    }

    stages {
        stage("Maven Build") {
            steps {
                sh "mvn -f Calculator/pom.xml clean install"
            }
        }

        stage("Unit Testing") {
            steps {
                sh "mvn -f Calculator/pom.xml test"
            }
        }
    }
}
